#!/usr/bin/env python3
"""make_BZV2_3.py

Bundled with bnp_na V13.6 from the standalone make_BZV2_3.py script.

Build a multi-segment B-DNA / Z-DNA construct connected by one or more BZ-junction cores.

You provide an alternating list of DNA helix PDBs:
    B1.pdb Z1.pdb B2.pdb Z2.pdb ...

The script inserts a copy of the template BZ-junction (core_BZ.py) between every adjacent
pair of helices, aligns it using sugar atoms (C1',C2',C3',C4',O5',C5'), trims overlapping
base pairs at helix ends (keeps the full core), and finally “ligates” the construct by
outputting *two* continuous DNA strands in a single PDB.

Key behaviour:
  * The input files are assumed to alternate B/Z by order, starting with B.
  * One fresh core_BZ copy is inserted between every adjacent helix pair.
  * B-side fits use 2 bp; Z-side fits use the outermost 1 bp from core_BZ aligned to
    the second bp from the chosen Z-helix end.
  * Axis handling has distinct modes:
      - codirectional (default): rotate the moving helix so its axis direction matches
        the fixed helix axis, but do not apply a lateral axis-line translation. This
        keeps the local junction geometry closer to the sugar-atom fit.
      - collinear: rotate as above, then translate the moving helix laterally so the
        fitted axis lines lie on the same spatial line. This is stricter but can
        stretch junction contacts, so it is no longer the default.
      - none: use only the local junction fit.
    No deliberate rotation about the helical axis is applied by either axis mode.
  * Axis lines for the post-fit axis correction can be estimated using DSSR via
    the imported align2z.py module (default: auto = try DSSR first, fall back to PCA).
  * The final ligated output is numbered 5' -> 3' for both strands.
  * A raw aligned PDB is also written with _raw before the extension. It is aligned
    but not junction-trimmed or ligated.

Z-DNA input requirement and automatic correction:
  * Each input Z-DNA model should be an alternating pyrimidine/purine Z-DNA duplex.
  * For make_BZ, each selected main chain should start with a pyrimidine (C/T/U)
    and end with a purine (A/G) in residue-number order. This puts the terminal
    dinucleotide phase in register with the Z end of core_BZ.
  * If a Z model does not meet this requirement, make_BZV2_3.py tries to pre-trim
    at most 1 base pair from each sequence end to satisfy it. A WARNING is printed
    whenever this automatic Z pre-trimming is applied. For Z-DNA generated by
    DSSR or bnp_na in this workflow, prepare the original Z-DNA input 2 bp
    longer than the target final Z segment so this
    terminal correction can remove 1 bp from each end when needed.
  * If no allowed terminal trim can satisfy the requirement, the script stops with
    an explicit error.

GUI mode:
  * If run with no arguments, or with --gui, a Tkinter GUI is opened so you can choose
    input files and parameters interactively.

Notes / assumptions:
  * Each input helix should be double-stranded DNA with two main chains.
  * ANISOU lines are ignored automatically because edit_pdb_atom.file2rec only parses
    ATOM/HETATM/TER records.
  * “Ligation” here means generating continuous chains (no TER breaks) and consistent
    residue numbering; PDB does not store explicit covalent bonds.

Example CLI:
    python make_BZV2_3.py --out multi_BZ.pdb B1.pdb Z1.pdb

    # Optional strict same-line correction:
    python make_BZV2_3.py --axis-mode collinear --out multi_BZ.pdb B1.pdb Z1.pdb

Dependencies:
  * numpy
  * tkinter (optional; only for GUI mode)
  * edit_pdb_atom.py (provided by you)
  * core_BZ.py (template core module generated from your trimmed 5zup structure)
  * align2z.py (imported, not modified; used for DSSR --more axis extraction when available)
"""

from __future__ import annotations

import argparse
import copy
import importlib
import math
import shlex
import sys
import tempfile
import types
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np

import core_BZ
from edit_pdb_atom import file2rec, pdb_atom_record, pdb_ter_record, rec2file



# Optional DSSR axis support. align2z.py belongs to a larger package; do not modify it.
# The helper functions below import it lazily for DSSR --more axis extraction.


def _is_atom_record(rec: object) -> bool:
    """True for ATOM/HETATM records parsed by edit_pdb_atom (excludes TER)."""
    return isinstance(rec, pdb_atom_record) and not isinstance(rec, pdb_ter_record)


# ----------------------------
# PDB / residue helpers
# ----------------------------

# Try both modern (prime) and legacy (star) atom naming.
_ATOM_NAME_ALIASES: Dict[str, List[str]] = {
    "C1'": ["C1'", "C1*"],
    "C2'": ["C2'", "C2*"],
    "C3'": ["C3'", "C3*"],
    "C4'": ["C4'", "C4*"],
    "C5'": ["C5'", "C5*"],
    "O3'": ["O3'", "O3*"],
    "O5'": ["O5'", "O5*"],
}

SUGAR_ATOMS: List[str] = list(core_BZ.SUGAR_ATOMS)
DEFAULT_OUTPUT_NAME = "make_BZ_out.pdb"


ResidKey = Tuple[str, str, int]  # (seg_id, chainID, resSeq)


@dataclass
class Residue:
    key: ResidKey
    chainID: str
    resSeq: int
    resName: str
    atoms: List[pdb_atom_record]
    atom_by_name: Dict[str, pdb_atom_record]

    def xyz(self, atom_name: str) -> Optional[np.ndarray]:
        """Return xyz for a requested atom name (with alias support), else None."""
        aliases = _ATOM_NAME_ALIASES.get(atom_name, [atom_name])
        for nm in aliases:
            rec = self.atom_by_name.get(nm)
            if rec is not None:
                return np.array([rec.x, rec.y, rec.z], dtype=float)
        return None


@dataclass
class Structure:
    name: str
    seg_id: str
    records: List[object]  # pdb_atom_record | pdb_ter_record
    residues: Dict[ResidKey, Residue]
    chains: List[str]  # chosen two main chain IDs, in internal order
    basepairs: List[Tuple[ResidKey, ResidKey]]  # physical order start->end

    # Which physical end was used to connect to the *previous* junction:
    #   'start' or 'end'.
    # For the first helix we set backward_end='start' so the default forward connection uses 'end'.
    backward_end: str = 'start'

    # Residues to delete at the end (overlaps with core)
    trim: set = None

    # Residues removed during input preprocessing (currently used for Z-DNA
    # terminal phase correction). These are excluded from alignment, raw output,
    # and final output.
    pre_trim: set = None

    def __post_init__(self):
        if self.trim is None:
            self.trim = set()
        if self.pre_trim is None:
            self.pre_trim = set()

    def forward_end(self) -> str:
        return 'end' if self.backward_end == 'start' else 'start'

    def _end_indices(self, end: str, n_bp: int = 2) -> List[int]:
        if len(self.basepairs) < n_bp:
            raise ValueError(f"{self.name}: need at least {n_bp} basepairs, found {len(self.basepairs)}")
        if end == 'end':
            # interior -> outer already
            return list(range(len(self.basepairs) - n_bp, len(self.basepairs)))
        if end == 'start':
            # basepairs[0] is outermost at start; return interior->outer
            return list(reversed(range(0, n_bp)))
        raise ValueError(f"end must be 'start' or 'end', got {end}")

    def end_basepairs(self, end: str, n_bp: int = 2) -> List[Tuple[ResidKey, ResidKey]]:
        idxs = self._end_indices(end, n_bp=n_bp)
        return [self.basepairs[i] for i in idxs]

    def axis_line(self, extra_exclude: Optional[set] = None) -> Tuple[np.ndarray, np.ndarray]:
        """Estimate helical axis line by PCA on active C1' atoms.

        Returns ``(point, direction)``, where ``point`` is the centroid of active
        C1' atoms and ``direction`` is a unit vector along the best-fit line.
        Active residues exclude preprocessing trims, junction trims, and optional
        extra exclusions supplied by the caller.
        """

        if extra_exclude is None:
            extra_exclude = set()
        coords: List[np.ndarray] = []
        for res in self.residues.values():
            if res.key in self.pre_trim or res.key in self.trim or res.key in extra_exclude:
                continue
            c1 = res.xyz("C1'")
            if c1 is not None:
                coords.append(c1)
        if len(coords) < 3:
            raise ValueError(f"{self.name}: cannot estimate axis (found {len(coords)} C1' atoms)")
        X = np.stack(coords, axis=0)
        point = X.mean(axis=0)
        Xc = X - point
        _, _, vt = np.linalg.svd(Xc, full_matrices=False)
        axis = vt[0]
        axis = axis / np.linalg.norm(axis)
        return point, axis

    def axis_vector(self) -> np.ndarray:
        """Estimate helical axis direction using PCA on active C1' atoms."""

        return self.axis_line()[1]




@dataclass
class JunctionInfo:
    jid: int
    fixed: Structure
    fixed_end: str
    core: Structure
    core_end_fixed: str  # 'B' or 'Z'
    swap_fixed_to_core: bool
    next_helix: Structure
    next_end: str
    core_end_next: str   # 'B' or 'Z'
    swap_next_to_core: bool
# ----------------------------
# Geometry
# ----------------------------

def kabsch(P: np.ndarray, Q: np.ndarray) -> Tuple[np.ndarray, np.ndarray, float]:
    """Return (R, t, rmsd) minimizing ||(R P + t) - Q|| for corresponding point sets.

    P, Q: (N,3)
    """
    if P.shape != Q.shape or P.ndim != 2 or P.shape[1] != 3:
        raise ValueError(f"Kabsch: bad shapes P={P.shape}, Q={Q.shape}")

    Pc = P.mean(axis=0)
    Qc = Q.mean(axis=0)
    P0 = P - Pc
    Q0 = Q - Qc
    H = P0.T @ Q0
    U, S, Vt = np.linalg.svd(H)
    R = Vt.T @ U.T
    if np.linalg.det(R) < 0:
        Vt[-1, :] *= -1
        R = Vt.T @ U.T
    t = Qc - R @ Pc
    Pfit = (R @ P.T).T + t
    rmsd = float(np.sqrt(np.mean(np.sum((Pfit - Q) ** 2, axis=1))))
    return R, t, rmsd


def rotation_matrix_from_vectors(v_from: np.ndarray, v_to: np.ndarray) -> np.ndarray:
    """Minimal rotation that maps v_from to v_to (both 3D)."""
    v1 = v_from / np.linalg.norm(v_from)
    v2 = v_to / np.linalg.norm(v_to)
    c = float(np.dot(v1, v2))
    # Clamp for numeric stability
    c = max(-1.0, min(1.0, c))

    if c > 0.999999:
        return np.eye(3)

    if c < -0.999999:
        # 180 degree rotation around any axis orthogonal to v1
        # Pick a stable orthogonal axis.
        ortho = np.array([1.0, 0.0, 0.0])
        if abs(v1[0]) > 0.9:
            ortho = np.array([0.0, 1.0, 0.0])
        axis = np.cross(v1, ortho)
        axis = axis / np.linalg.norm(axis)
        return rodrigues(axis, math.pi)

    axis = np.cross(v1, v2)
    s = np.linalg.norm(axis)
    axis = axis / s
    angle = math.atan2(s, c)
    return rodrigues(axis, angle)


def rodrigues(axis: np.ndarray, angle: float) -> np.ndarray:
    """Rodrigues' rotation formula for unit axis."""
    ax = axis / np.linalg.norm(axis)
    K = np.array(
        [[0.0, -ax[2], ax[1]], [ax[2], 0.0, -ax[0]], [-ax[1], ax[0], 0.0]], dtype=float
    )
    I = np.eye(3)
    return I + math.sin(angle) * K + (1.0 - math.cos(angle)) * (K @ K)


def apply_rigid_transform(records: List[object], R: np.ndarray, t: np.ndarray) -> None:
    """In-place rigid transform of all ATOM/HETATM records."""
    for rec in records:
        if _is_atom_record(rec):
            xyz = np.array([rec.x, rec.y, rec.z], dtype=float)
            new = R @ xyz + t
            rec.update_xyz(float(new[0]), float(new[1]), float(new[2]))


def apply_rotation_about_point(records: List[object], R: np.ndarray, pivot: np.ndarray) -> None:
    """In-place rotation of all ATOM/HETATM records about a pivot point."""
    for rec in records:
        if _is_atom_record(rec):
            xyz = np.array([rec.x, rec.y, rec.z], dtype=float)
            new = R @ (xyz - pivot) + pivot
            rec.update_xyz(float(new[0]), float(new[1]), float(new[2]))


def apply_translation(records: List[object], shift: np.ndarray) -> None:
    """In-place translation of all ATOM/HETATM records."""

    for rec in records:
        if _is_atom_record(rec):
            rec.update_xyz(float(rec.x + shift[0]), float(rec.y + shift[1]), float(rec.z + shift[2]))


def axis_line_distance(p1: np.ndarray, u: np.ndarray, p2: np.ndarray, v: np.ndarray) -> float:
    """Shortest distance between two 3D lines p1+t*u and p2+s*v."""

    u = u / np.linalg.norm(u)
    v = v / np.linalg.norm(v)
    w = p2 - p1
    c = np.cross(u, v)
    nc = float(np.linalg.norm(c))
    if nc < 1e-10:
        return float(np.linalg.norm(w - np.dot(w, u) * u))
    return float(abs(np.dot(w, c / nc)))


def perpendicular_shift_to_collinear(fixed_point: np.ndarray, fixed_dir: np.ndarray, moving_point: np.ndarray) -> np.ndarray:
    """Return a pure lateral shift that puts the moving axis point on the fixed axis line."""

    u = fixed_dir / np.linalg.norm(fixed_dir)
    delta = fixed_point - moving_point
    return delta - np.dot(delta, u) * u




@dataclass
class AxisLineResult:
    point: np.ndarray
    direction: np.ndarray
    source: str
    detail: str = ""


_ALIGN2Z_MODULE = None
_ALIGN2Z_IMPORT_ERROR: Optional[BaseException] = None
_DSSR_AUTO_FALLBACK_REPORTED = False


def _install_geometry_utils_stub_for_align2z() -> None:
    """Install a tiny in-memory geometry_utils fallback so align2z.py can import.

    Some distributions of align2z.py live inside a larger package that provides
    geometry_utils.py. We do not modify align2z.py; this only supplies the two names
    it imports if that package module is absent in the current folder.
    """

    if "geometry_utils" in sys.modules:
        return

    mod = types.ModuleType("geometry_utils")

    class GeometryError(Exception):
        pass

    def rotation_matrix_from_to(v_from, v_to):
        try:
            return rotation_matrix_from_vectors(np.asarray(v_from, dtype=float), np.asarray(v_to, dtype=float))
        except Exception as exc:
            raise GeometryError(str(exc)) from exc

    mod.GeometryError = GeometryError
    mod.rotation_matrix_from_to = rotation_matrix_from_to
    sys.modules["geometry_utils"] = mod


def _get_align2z_module():
    """Import align2z.py lazily without modifying that file."""

    global _ALIGN2Z_MODULE, _ALIGN2Z_IMPORT_ERROR
    if _ALIGN2Z_MODULE is not None:
        return _ALIGN2Z_MODULE

    try:
        _ALIGN2Z_MODULE = importlib.import_module("align2z")
        return _ALIGN2Z_MODULE
    except ModuleNotFoundError as exc:
        if exc.name != "geometry_utils":
            _ALIGN2Z_IMPORT_ERROR = exc
            raise
        sys.modules.pop("align2z", None)
        _install_geometry_utils_stub_for_align2z()
        try:
            _ALIGN2Z_MODULE = importlib.import_module("align2z")
            return _ALIGN2Z_MODULE
        except BaseException as exc2:
            _ALIGN2Z_IMPORT_ERROR = exc2
            raise
    except BaseException as exc:
        _ALIGN2Z_IMPORT_ERROR = exc
        raise


def _active_structure_records_for_axis(struct: Structure, extra_exclude: Optional[set] = None) -> List[object]:
    """Return deep-copied ATOM/TER records for active residues used by DSSR.

    ``rec2file(..., reorder_serial=True)`` mutates record serial numbers, so this
    function always deep-copies atom records before writing the temporary PDB.
    """

    if extra_exclude is None:
        extra_exclude = set()
    out_recs: List[object] = []
    for chainID in struct.chains:
        keys = [
            k for k, r in struct.residues.items()
            if r.chainID == chainID and k not in struct.pre_trim and k not in struct.trim and k not in extra_exclude
        ]
        keys.sort(key=lambda k: struct.residues[k].resSeq)
        if not keys:
            continue
        for key in keys:
            out_recs.extend(copy.deepcopy(struct.residues[key].atoms))
        last_res = struct.residues[keys[-1]]
        line = f"TER   {0:5d}      {last_res.resName:>3} {chainID}{last_res.resSeq:4d}\n"
        out_recs.append(pdb_ter_record(line))
    return out_recs


def axis_line_dssr(struct: Structure, extra_exclude: Optional[set] = None) -> AxisLineResult:
    """Estimate a helix axis line using DSSR --more through imported align2z.py."""

    align2z_mod = _get_align2z_module()
    with tempfile.TemporaryDirectory(prefix="make_BZ_axis_") as tmpdir:
        tmp = Path(tmpdir)
        safe_name = struct.name.replace('/', '_').replace(' ', '_')
        pdb_path = tmp / f"{struct.seg_id}_{safe_name}_axis.pdb"
        out_txt = tmp / f"{struct.seg_id}_dssr_more.out"
        recs = _active_structure_records_for_axis(struct, extra_exclude=extra_exclude)
        if not recs:
            raise RuntimeError(f"{struct.name}: no active records available for DSSR axis fitting")
        with pdb_path.open("w", encoding="utf-8") as fout:
            rec2file(recs, fout, reorder_serial=True)
            fout.write("END\n")

        ok, dssr_log, cmd = align2z_mod.run_dssr_more_axis(pdb_path, out_txt, cwd=tmp)
        cmd_text = align2z_mod.command_to_text(cmd) if cmd else "x3dna-dssr command unavailable"
        if not ok or not out_txt.exists():
            raise RuntimeError(
                "DSSR --more axis extraction failed. "
                f"Command: {cmd_text}. Output: {dssr_log or '(no output)'}"
            )
        p1, p2 = align2z_mod.parse_first_axis_points(out_txt)
        p1_arr = np.asarray(p1, dtype=float)
        p2_arr = np.asarray(p2, dtype=float)
        v = p2_arr - p1_arr
        n = float(np.linalg.norm(v))
        if n < 1e-8:
            raise RuntimeError("DSSR point-one and point-two define a near-zero axis length")
        return AxisLineResult(
            point=p1_arr,
            direction=v / n,
            source="DSSR/align2z",
            detail=f"command={cmd_text}; point-one={p1_arr.tolist()}; point-two={p2_arr.tolist()}",
        )


def axis_line_pca(struct: Structure, extra_exclude: Optional[set] = None) -> AxisLineResult:
    point, direction = struct.axis_line(extra_exclude=extra_exclude)
    return AxisLineResult(point=point, direction=direction, source="PCA(C1')", detail="fallback/local PCA")


def get_axis_line(
    struct: Structure,
    *,
    source: str,
    extra_exclude: Optional[set] = None,
    verbose_prefix: str = "",
    label: str = "helix",
) -> AxisLineResult:
    """Return an axis line using DSSR/align2z, PCA, or auto fallback."""

    global _DSSR_AUTO_FALLBACK_REPORTED
    src = (source or "auto").strip().lower()
    if src not in ("auto", "dssr", "pca"):
        raise ValueError(f"Unknown axis source: {source}")

    if src in ("auto", "dssr"):
        try:
            result = axis_line_dssr(struct, extra_exclude=extra_exclude)
            print(f"{verbose_prefix} axis[{label}] source={result.source}; {result.detail}")
            return result
        except BaseException as exc:
            if src == "dssr":
                raise RuntimeError(f"DSSR axis source requested but failed for {struct.name}: {exc}") from exc
            if not _DSSR_AUTO_FALLBACK_REPORTED:
                print(
                    f"{verbose_prefix} WARNING: DSSR/align2z axis extraction failed in auto mode; "
                    f"falling back to PCA(C1') for this run. Reason: {exc}"
                )
                _DSSR_AUTO_FALLBACK_REPORTED = True

    result = axis_line_pca(struct, extra_exclude=extra_exclude)
    print(f"{verbose_prefix} axis[{label}] source={result.source}; {result.detail}")
    return result


# ----------------------------
# Parsing and basepair detection
# ----------------------------

def load_pdb_records(path: Path) -> List[object]:
    recs: List[object] = []
    with path.open('r') as f:
        file2rec(f, recs)
    return recs


def build_residues(records: List[object], seg_id: str) -> Dict[ResidKey, Residue]:
    # Group ATOM/HETATM by (chainID,resSeq)
    tmp: Dict[Tuple[str, int], List[pdb_atom_record]] = {}
    resname_by: Dict[Tuple[str, int], str] = {}
    for rec in records:
        if not _is_atom_record(rec):
            continue
        key2 = (rec.chainID, rec.resSeq)
        tmp.setdefault(key2, []).append(rec)
        resname_by[key2] = rec.resName

    residues: Dict[ResidKey, Residue] = {}
    for (chainID, resSeq), atomrecs in tmp.items():
        key: ResidKey = (seg_id, chainID, resSeq)
        atom_by_name: Dict[str, pdb_atom_record] = {}
        for a in atomrecs:
            # Keep first occurrence; for altloc situations you might improve this.
            atom_by_name.setdefault(a.name, a)
        residues[key] = Residue(
            key=key,
            chainID=chainID,
            resSeq=resSeq,
            resName=resname_by[(chainID, resSeq)],
            atoms=atomrecs,
            atom_by_name=atom_by_name,
        )
    return residues


def pick_two_main_chains(residues: Dict[ResidKey, Residue]) -> List[str]:
    counts: Dict[str, int] = {}
    for res in residues.values():
        counts[res.chainID] = counts.get(res.chainID, 0) + 1
    if len(counts) < 2:
        raise ValueError(f"Need >=2 chains for dsDNA, found chains={sorted(counts)}")
    # Pick top-2 by residue count, tie-break by chainID
    chains = sorted(counts.keys(), key=lambda c: (-counts[c], c))[:2]
    return chains


def compute_axis_and_projections(
    residues: Dict[ResidKey, Residue],
    chains: List[str],
    exclude: Optional[set] = None,
) -> Tuple[np.ndarray, Dict[ResidKey, float]]:
    if exclude is None:
        exclude = set()
    coords: List[np.ndarray] = []
    keys: List[ResidKey] = []
    for key, res in residues.items():
        if key in exclude:
            continue
        if res.chainID not in chains:
            continue
        c1 = res.xyz("C1'")
        if c1 is None:
            continue
        coords.append(c1)
        keys.append(key)
    if len(coords) < 6:
        raise ValueError(f"Cannot compute axis: only {len(coords)} residues with C1' in main chains {chains}")
    X = np.stack(coords, axis=0)
    mean = X.mean(axis=0)
    Xc = X - mean
    _, _, vt = np.linalg.svd(Xc, full_matrices=False)
    axis = vt[0]
    axis = axis / np.linalg.norm(axis)

    # Choose axis sign so that along the first chain, projections correlate positively with resSeq.
    chain0 = chains[0]
    seqs = []
    ts = []
    for key, res in residues.items():
        if key in exclude:
            continue
        if res.chainID != chain0:
            continue
        c1 = res.xyz("C1'")
        if c1 is None:
            continue
        t = float(np.dot(c1 - mean, axis))
        seqs.append(res.resSeq)
        ts.append(t)
    if len(seqs) >= 3:
        corr = np.corrcoef(seqs, ts)[0, 1]
        if not np.isnan(corr) and corr < 0:
            axis = -axis

    proj: Dict[ResidKey, float] = {}
    for key, res in residues.items():
        if key in exclude:
            continue
        if res.chainID not in chains:
            continue
        c1 = res.xyz("C1'")
        if c1 is None:
            continue
        proj[key] = float(np.dot(c1 - mean, axis))
    return axis, proj


def build_basepairs(
    residues: Dict[ResidKey, Residue],
    chains: List[str],
    exclude: Optional[set] = None,
) -> List[Tuple[ResidKey, ResidKey]]:
    if exclude is None:
        exclude = set()
    axis, proj = compute_axis_and_projections(residues, chains, exclude=exclude)
    # Sort residues in each chain by projection (physical order)
    chain_res: Dict[str, List[ResidKey]] = {chains[0]: [], chains[1]: []}
    for key, res in residues.items():
        if key in exclude:
            continue
        if res.chainID in chain_res and key in proj:
            chain_res[res.chainID].append(key)

    for c in chain_res:
        chain_res[c].sort(key=lambda k: proj[k])

    n = min(len(chain_res[chains[0]]), len(chain_res[chains[1]]))
    if n < 2:
        raise ValueError(f"Not enough residues to form basepairs: chain lengths {[len(chain_res[c]) for c in chains]}")

    bp: List[Tuple[ResidKey, ResidKey]] = []
    for i in range(n):
        bp.append((chain_res[chains[0]][i], chain_res[chains[1]][i]))
    return bp


def load_helix(path: Path, seg_id: str) -> Structure:
    records = load_pdb_records(path)
    residues = build_residues(records, seg_id=seg_id)
    chains = pick_two_main_chains(residues)
    basepairs = build_basepairs(residues, chains)
    return Structure(name=path.name, seg_id=seg_id, records=records, residues=residues, chains=chains, basepairs=basepairs)


def new_core(seg_id: str) -> Structure:
    records = core_BZ.core_records()
    residues = build_residues(records, seg_id=seg_id)
    chains = pick_two_main_chains(residues)
    basepairs = build_basepairs(residues, chains)
    return Structure(name=f"core_BZ({seg_id})", seg_id=seg_id, records=records, residues=residues, chains=chains, basepairs=basepairs)


# ----------------------------
# Z-DNA terminal phase preprocessing and direction helpers
# ----------------------------

PURINES = {'A', 'G'}
PYRIMIDINES = {'C', 'T', 'U'}


def _base_code(resName: str) -> Optional[str]:
    """Return A/C/G/T/U for common DNA/RNA residue names (DA/DC/... or A/C/...)."""

    s = (resName or '').strip().upper()
    for ch in reversed(s):
        if ch in {'A', 'C', 'G', 'T', 'U'}:
            return ch
    return None


def _chain_residues_by_resseq(struct: Structure, chainID: str, exclude: Optional[set] = None) -> List[Residue]:
    """Return residues in one chain sorted by residue number, excluding requested keys."""

    if exclude is None:
        exclude = set()
    residues = [r for r in struct.residues.values() if r.chainID == chainID and r.key not in exclude]
    residues.sort(key=lambda r: r.resSeq)
    return residues


def _z_requirement_status(struct: Structure, exclude: Optional[set] = None) -> Tuple[bool, List[str]]:
    """Check the make_BZ Z-DNA sequence-phase requirement.

    Requirement: every selected main chain should start with a pyrimidine and end with
    a purine in residue-number order. This is the Z-DNA terminal phase expected by the
    Z end of core_BZ.
    """

    if exclude is None:
        exclude = set()
    messages: List[str] = []
    ok_all = True
    for chainID in struct.chains:
        residues = _chain_residues_by_resseq(struct, chainID, exclude=exclude)
        if len(residues) < 3:
            ok_all = False
            messages.append(f"chain {chainID}: too few residues after trimming ({len(residues)})")
            continue
        first = _base_code(residues[0].resName)
        last = _base_code(residues[-1].resName)
        ok = first in PYRIMIDINES and last in PURINES
        ok_all = ok_all and ok
        messages.append(
            f"chain {chainID}: start={residues[0].resName}{residues[0].resSeq}({first}), "
            f"end={residues[-1].resName}{residues[-1].resSeq}({last}), ok={'Y' if ok else 'N'}"
        )
    return ok_all, messages


def _candidate_terminal_trim_keys(struct: Structure, start_bp_trim: int, end_bp_trim: int) -> set:
    """Return residue keys removed by trimming terminal bp from both chains by resSeq order."""

    trim_keys = set()
    for chainID in struct.chains:
        residues = _chain_residues_by_resseq(struct, chainID)
        if start_bp_trim + end_bp_trim >= len(residues) - 2:
            # Leave at least three residues per chain for a meaningful helix end/anchor.
            return set(struct.residues.keys())
        trim_keys.update(r.key for r in residues[:start_bp_trim])
        if end_bp_trim:
            trim_keys.update(r.key for r in residues[-end_bp_trim:])
    return trim_keys


def apply_z_auto_trim_if_needed(struct: Structure, filename: str) -> None:
    """Pre-trim terminal Z-DNA bp when needed to satisfy the required terminal phase.

    If the untrimmed Z model already satisfies the requirement, no changes are made.
    Otherwise the function tries four possibilities: no extra trim, 1 bp from the
    sequence start, 1 bp from the sequence end, or 1 bp from both ends. It chooses
    the solution with the fewest total removed base pairs. The selected residues are
    stored in ``struct.pre_trim`` and the structure's basepair list is rebuilt using
    only the remaining residues.
    """

    ok, messages = _z_requirement_status(struct, exclude=struct.pre_trim)
    if ok:
        print(f"  Z-check OK for {filename}: each main chain starts with pyrimidine and ends with purine.")
        for msg in messages:
            print(f"    {msg}")
        return

    print(f"  WARNING: Z-check failed for {filename}; trying terminal Z-DNA pre-trimming.")
    for msg in messages:
        print(f"    before: {msg}")

    best = None
    for total in range(0, 3):
        for start_trim in range(0, 2):
            for end_trim in range(0, 2):
                if start_trim + end_trim != total:
                    continue
                candidate = _candidate_terminal_trim_keys(struct, start_trim, end_trim)
                ok_candidate, candidate_messages = _z_requirement_status(struct, exclude=candidate)
                if ok_candidate:
                    best = (start_trim, end_trim, candidate, candidate_messages)
                    break
            if best is not None:
                break
        if best is not None:
            break

    if best is None:
        raise SystemExit(
            f"ERROR: Z-DNA file {filename} does not satisfy the required terminal phase, and no "
            f"auto-trim solution was found when allowing at most 1 bp removal from each Z-DNA end. "
            "Expected each main chain to start with pyrimidine (C/T/U) and end with purine (A/G)."
        )

    start_trim, end_trim, trim_keys, after_messages = best
    struct.pre_trim.update(trim_keys)
    struct.basepairs = build_basepairs(struct.residues, struct.chains, exclude=struct.pre_trim)

    print(
        f"  WARNING: Z-DNA file {filename} was pre-trimmed to satisfy terminal phase: "
        f"start_bp_trim={start_trim}, end_bp_trim={end_trim}, residues_removed={len(trim_keys)}."
    )
    print("  The raw aligned PDB and final ligated PDB will exclude these pre-trimmed terminal residues.")
    for msg in after_messages:
        print(f"    after:  {msg}")
    print(f"  Z-check OK after pre-trimming; active basepairs={len(struct.basepairs)}")


def _bp_centroid(struct: Structure, bp: Tuple[ResidKey, ResidKey], atom: str = "C1'") -> np.ndarray:
    pts: List[np.ndarray] = []
    for rk in bp:
        xyz = struct.residues[rk].xyz(atom)
        if xyz is None:
            raise ValueError(f"{struct.name}: missing {atom} on residue {rk[1]}{rk[2]}")
        pts.append(xyz)
    return np.mean(np.stack(pts, axis=0), axis=0)


def end_outward_vector(struct: Structure, end: str) -> np.ndarray:
    """Unit vector pointing from the helix interior towards the requested physical end."""

    bps = struct.end_basepairs(end, n_bp=2)  # interior -> outer
    inner = _bp_centroid(struct, bps[0])
    outer = _bp_centroid(struct, bps[1])
    v = outer - inner
    n = np.linalg.norm(v)
    if n < 1e-8:
        raise ValueError(f"{struct.name}: cannot define outward vector at {end} (degenerate)")
    return v / n


def core_through_vector(core: Structure, core_end_fixed: str, core_end_next: str) -> np.ndarray:
    """Unit vector from the core's fixed-side outer bp to its next-side outer bp."""

    bp_fixed = _core_outer_basepair(core, core_end_fixed)
    bp_next = _core_outer_basepair(core, core_end_next)
    p_fixed = _bp_centroid(core, bp_fixed)
    p_next = _bp_centroid(core, bp_next)
    v = p_next - p_fixed
    n = np.linalg.norm(v)
    if n < 1e-8:
        raise ValueError(f"{core.name}: cannot define through-vector (degenerate)")
    return v / n


# ----------------------------
# Alignment & assembly
# ----------------------------

def _coords_for_basepairs(struct: Structure, bps: List[Tuple[ResidKey, ResidKey]], swap_strands: bool) -> np.ndarray:
    pts: List[np.ndarray] = []
    for (r1, r2) in bps:
        if swap_strands:
            r1, r2 = r2, r1
        for rk in (r1, r2):
            res = struct.residues[rk]
            for at in SUGAR_ATOMS:
                xyz = res.xyz(at)
                if xyz is None:
                    raise ValueError(f"{struct.name}: residue {res.chainID}{res.resSeq} missing atom {at} (or alias)")
                pts.append(xyz)
    return np.stack(pts, axis=0)


def align_moving_to_fixed(
    *,
    fixed: Structure,
    fixed_end: str,
    moving: Structure,
    moving_end_kind: str,
    core_end: str,
    verbose_prefix: str,
) -> Tuple[float, bool]:
    """Align a moving *core* end onto a fixed helix end.

    Alignment atoms are the sugar atoms listed in ``SUGAR_ATOMS``.

    Rules:
      * If ``core_end == 'B'``: fit using 2 bp (core B-end 2 bp <-> helix end 2 bp).
      * If ``core_end == 'Z'`` (v1.1 behaviour): fit using **only the outermost 1 bp**
        from the core's Z-end, aligned to the **second bp** from the helix end.

    Returns
    -------
    (rmsd, swap_strands)
      swap_strands refers to whether we had to swap the *fixed* helix strand mapping
      to get the lowest RMSD.
    """

    if moving_end_kind != 'core':
        raise ValueError("align_moving_to_fixed only supports moving_end_kind='core' here")

    # Decide which basepairs to use for alignment.
    if core_end == 'B':
        # For B-end: use helix end basepairs in outer->inner order so that after trimming 2 bp,
        # the helix *anchor* bp (3rd from end) sits adjacent to the core *outer* bp.
        fixed_bps = list(reversed(fixed.end_basepairs(fixed_end, n_bp=2)))
        bps_raw = list(core_BZ.B_END_BASEPAIRS)  # interior -> outer
        note = '2bp (helix order outer->inner)'
    elif core_end == 'Z':
        # Use the *second* bp from the helix end (index 0 in our interior->outer list)
        fixed_bps2 = fixed.end_basepairs(fixed_end, n_bp=2)
        fixed_bps = [fixed_bps2[0]]

        # Use only the *outermost* bp from the core Z-end (last in interior->outer list)
        bps_raw_all = list(core_BZ.Z_END_BASEPAIRS)
        bps_raw = [bps_raw_all[-1]]
        note = '1bp(core outer) -> helix second bp'
    else:
        raise ValueError(f"core_end must be 'B' or 'Z', got {core_end}")

    # Convert (chain,resSeq) -> ResidKey
    moving_bps: List[Tuple[ResidKey, ResidKey]] = []
    for (a, b) in bps_raw:
        ka: ResidKey = (moving.seg_id, a[0], int(a[1]))
        kb: ResidKey = (moving.seg_id, b[0], int(b[1]))
        moving_bps.append((ka, kb))

    best = None
    for swap in (False, True):
        P = _coords_for_basepairs(moving, moving_bps, swap_strands=False)  # core: keep as-is
        Q = _coords_for_basepairs(fixed, fixed_bps, swap_strands=swap)
        R, t, rmsd = kabsch(P, Q)
        if best is None or rmsd < best[0]:
            best = (rmsd, swap, R, t)

    assert best is not None
    rmsd, swap, R, t = best

    apply_rigid_transform(moving.records, R, t)

    print(
        f"{verbose_prefix} align core({core_end}-end) -> fixed[{fixed.name}] {fixed_end}-end: "
        f"rmsd={rmsd:.3f} A, strand_swap={'Y' if swap else 'N'}  [{note}]"
    )
    return rmsd, swap


def align_helix_to_core(
    *,
    helix: Structure,
    preferred_end: str,
    core: Structure,
    core_end: str,
    junction_dir: np.ndarray,
    verbose_prefix: str,
    auto_switch_if_better: bool = True,
) -> Tuple[str, float, bool, np.ndarray, float]:
    """Move a helix onto a positioned core end.

    We test both strand-mapping options (swap / no swap). Optionally we also test
    the opposite helix end. A candidate is preferred only if the far end of the
    helix extends forward along ``junction_dir`` (fixed helix -> core -> next helix),
    which prevents fold-back overlap.

    Rules:
      * If ``core_end == 'B'``: fit using 2 bp (helix end 2 bp <-> core B-end 2 bp).
      * If ``core_end == 'Z'``: fit using only the outermost 1 bp from the core Z-end,
        aligned to the second bp from the chosen helix end.

    Returns:
      chosen_end, rmsd, strand_swap, pivot_xyz, direction_cosine
    """

    if core_end == 'B':
        bps_raw = list(core_BZ.B_END_BASEPAIRS)  # interior -> outer
        note = '2bp'
    elif core_end == 'Z':
        bps_raw_all = list(core_BZ.Z_END_BASEPAIRS)
        bps_raw = [bps_raw_all[-1]]  # outermost Z-end bp in core_BZ
        note = '1bp(core outer) -> helix second bp'
    else:
        raise ValueError(f"core_end must be 'B' or 'Z', got {core_end}")

    core_bps: List[Tuple[ResidKey, ResidKey]] = []
    for (a, b) in bps_raw:
        ka: ResidKey = (core.seg_id, a[0], int(a[1]))
        kb: ResidKey = (core.seg_id, b[0], int(b[1]))
        core_bps.append((ka, kb))

    candidate_ends = [preferred_end]
    other_end = 'start' if preferred_end == 'end' else 'end'
    if auto_switch_if_better:
        candidate_ends.append(other_end)

    Qcore = _coords_for_basepairs(core, core_bps, swap_strands=False)
    pivot = Qcore.mean(axis=0)

    best_good = None
    best_any = None

    for helix_end in candidate_ends:
        if core_end == 'B':
            helix_bps = list(reversed(helix.end_basepairs(helix_end, n_bp=2)))
        else:
            helix_bps2 = helix.end_basepairs(helix_end, n_bp=2)
            helix_bps = [helix_bps2[0]]  # second bp from this Z helix end

        if helix_end == 'start':
            bp_connect = helix.basepairs[0]
            bp_far = helix.basepairs[-1]
        else:
            bp_connect = helix.basepairs[-1]
            bp_far = helix.basepairs[0]
        p_connect0 = _bp_centroid(helix, bp_connect)
        p_far0 = _bp_centroid(helix, bp_far)

        for swap in (False, True):
            P = _coords_for_basepairs(helix, helix_bps, swap_strands=swap)
            R, t, rmsd = kabsch(P, Qcore)

            p_connect = R @ p_connect0 + t
            p_far = R @ p_far0 + t
            ext = p_far - p_connect
            ext_len = float(np.linalg.norm(ext))
            proj = float(np.dot(ext, junction_dir))
            dot_unit = proj / ext_len if ext_len > 1e-12 else -1.0

            cand = (rmsd, helix_end, swap, R, t, dot_unit, proj)
            if best_any is None or rmsd < best_any[0]:
                best_any = cand
            if dot_unit > 0:
                if best_good is None or rmsd < best_good[0]:
                    best_good = cand

    assert best_any is not None
    chosen = best_good if best_good is not None else best_any
    rmsd, chosen_end, swap, R, t, dot_unit, proj = chosen

    apply_rigid_transform(helix.records, R, t)

    switched = (chosen_end != preferred_end)
    msg = (
        f"{verbose_prefix} align helix[{helix.name}] {chosen_end}-end -> core({core_end}-end): "
        f"rmsd={rmsd:.3f} A, strand_swap={'Y' if swap else 'N'}  [{note}]  "
        f"dir_cos={dot_unit:.3f} (proj={proj:.1f} A)"
    )
    if switched:
        msg += f"  (NOTE: preferred_end={preferred_end} but chose {chosen_end})"
    if best_good is None:
        msg += "  WARNING: no candidate satisfied forward-direction; using lowest RMSD anyway"
    print(msg)

    return chosen_end, rmsd, swap, pivot, dot_unit

def normalize_axis_mode(mode: Optional[str]) -> str:
    """Normalize user-facing axis-mode text."""

    m = (mode or 'codirectional').strip().lower()
    if m in ('collinear',):
        return 'collinear'
    if m in ('codirectional', 'co-directional', 'co_directional', 'direction', 'y', 'yes', 'true'):
        return 'codirectional'
    if m in ('none', 'n', 'no', 'false'):
        return 'none'
    raise ValueError(f"Unknown axis mode: {mode}")


def enforce_axis_alignment(
    *,
    fixed_helix: Structure,
    moving_helix: Structure,
    pivot: np.ndarray,
    junction_dir: np.ndarray,
    verbose_prefix: str,
    mode: str = 'codirectional',
    axis_source: str = 'auto',
    fixed_extra_exclude: Optional[set] = None,
    moving_extra_exclude: Optional[set] = None,
) -> None:
    """Enforce co-directional or true-collinear helix axes.

    ``mode='codirectional'`` reproduces the older behavior: it applies the minimal
    rotation that makes the moving helix axis direction parallel/co-directional with
    the fixed helix axis direction. This is an axis-tilt correction and does not
    intentionally rotate about the helical axis.

    ``mode='collinear'`` first performs the same direction correction, then translates
    the moving helix by the perpendicular offset needed to put the two fitted axis
    lines on the same infinite spatial line. The translation has no rotational
    component, so it also does not add twist.

    Axis lines are obtained by ``axis_source``: ``auto`` tries DSSR via imported
    align2z.py and falls back to PCA, ``dssr`` requires DSSR, and ``pca`` uses the
    original C1' PCA estimate.
    """

    normalized_mode = normalize_axis_mode(mode)
    if normalized_mode == 'none':
        print(f"{verbose_prefix} axis-mode=none: no post-fit axis correction applied.")
        return

    if fixed_extra_exclude is None:
        fixed_extra_exclude = set()
    if moving_extra_exclude is None:
        moving_extra_exclude = set()

    fixed_axis = get_axis_line(fixed_helix, source=axis_source, extra_exclude=fixed_extra_exclude, verbose_prefix=verbose_prefix, label='fixed')
    moving_axis = get_axis_line(moving_helix, source=axis_source, extra_exclude=moving_extra_exclude, verbose_prefix=verbose_prefix, label='moving-before')
    pf, u = fixed_axis.point, fixed_axis.direction
    pm, v = moving_axis.point, moving_axis.direction

    if np.dot(u, junction_dir) < 0:
        u = -u
    if np.dot(v, junction_dir) < 0:
        v = -v

    dot = float(np.dot(u, v))
    dot = max(-1.0, min(1.0, dot))
    angle_before = math.degrees(math.acos(dot))
    offset_before = axis_line_distance(pf, u, pm, v)

    if angle_before >= 1e-3:
        R = rotation_matrix_from_vectors(v, u)
        apply_rotation_about_point(moving_helix.records, R, pivot)

    moving_axis2 = get_axis_line(moving_helix, source=axis_source, extra_exclude=moving_extra_exclude, verbose_prefix=verbose_prefix, label='moving-after-rotation')
    pm2, v2 = moving_axis2.point, moving_axis2.direction
    if np.dot(v2, junction_dir) < 0:
        v2 = -v2
    dot2 = float(np.dot(u, v2))
    dot2 = max(-1.0, min(1.0, dot2))
    angle_after_rotation = math.degrees(math.acos(dot2))
    offset_after_rotation = axis_line_distance(pf, u, pm2, v2)

    if normalized_mode == 'codirectional':
        print(
            f"{verbose_prefix} codirectional: axis angle {angle_before:.3f} -> {angle_after_rotation:.3f} deg; "
            f"axis-line offset {offset_before:.3f} -> {offset_after_rotation:.3f} A (no axis-line shift)."
        )
        return

    shift = perpendicular_shift_to_collinear(pf, u, pm2)
    shift_mag = float(np.linalg.norm(shift))
    if shift_mag > 1e-8:
        apply_translation(moving_helix.records, shift)

    moving_axis3 = get_axis_line(moving_helix, source=axis_source, extra_exclude=moving_extra_exclude, verbose_prefix=verbose_prefix, label='moving-after-shift')
    pm3, v3 = moving_axis3.point, moving_axis3.direction
    if np.dot(v3, junction_dir) < 0:
        v3 = -v3
    dot3 = float(np.dot(u, v3))
    dot3 = max(-1.0, min(1.0, dot3))
    angle_after = math.degrees(math.acos(dot3))
    offset_after = axis_line_distance(pf, u, pm3, v3)

    print(
        f"{verbose_prefix} collinear: axis direction angle {angle_before:.3f} -> {angle_after_rotation:.3f} -> {angle_after:.3f} deg; "
        f"axis-line offset {offset_before:.3f} -> {offset_after_rotation:.3f} -> {offset_after:.3f} A; "
        f"perpendicular shift={shift_mag:.3f} A."
    )
    if shift_mag > 0.5:
        print(
            f"{verbose_prefix} WARNING: strict collinear mode shifted the moving helix by {shift_mag:.3f} A. "
            "This enforces a common axis line but may slightly worsen local junction contact geometry. "
            "Use the default --axis-mode codirectional for no-shift behavior."
        )


def enforce_collinear_axes(
    *,
    fixed_helix: Structure,
    moving_helix: Structure,
    pivot: np.ndarray,
    junction_dir: np.ndarray,
    verbose_prefix: str,
) -> None:
    """Backward-compatible wrapper: optional strict true-collinear mode."""

    enforce_axis_alignment(
        fixed_helix=fixed_helix,
        moving_helix=moving_helix,
        pivot=pivot,
        junction_dir=junction_dir,
        verbose_prefix=verbose_prefix,
        mode='collinear',
        axis_source='auto',
    )


# ----------------------------
# Final ligation / output
# ----------------------------

@dataclass
class ResidueNode:
    key: ResidKey
    residue: Residue
    P: Optional[np.ndarray]
    O3: Optional[np.ndarray]


def collect_residue_nodes(structs: Sequence[Structure]) -> List[ResidueNode]:
    nodes: List[ResidueNode] = []
    for st in structs:
        for key, res in st.residues.items():
            if key in st.pre_trim or key in st.trim:
                continue
            P = res.xyz('P')  # P is not in alias dict; direct lookup
            if P is None and 'P' in res.atom_by_name:
                rec = res.atom_by_name['P']
                P = np.array([rec.x, rec.y, rec.z], dtype=float)
            O3 = res.xyz("O3'")
            nodes.append(ResidueNode(key=key, residue=res, P=P, O3=O3))
    return nodes


def build_backbone_next(nodes: List[ResidueNode], dist_cutoff: float = 2.2) -> Tuple[Dict[int, int], Dict[int, float]]:
    """Build a mapping i->j meaning residue i's O3' is bonded to residue j's P.

    Returns (next_map, dist_map)
    """
    P_idx = [i for i, n in enumerate(nodes) if n.P is not None]
    O_idx = [i for i, n in enumerate(nodes) if n.O3 is not None]

    if not P_idx or not O_idx:
        raise ValueError("No P atoms or no O3' atoms found; cannot ligate")

    P_coords = np.stack([nodes[i].P for i in P_idx], axis=0)  # (nP,3)

    next_map: Dict[int, int] = {}
    dist_map: Dict[int, float] = {}

    for i in O_idx:
        o = nodes[i].O3
        # Compute distances to all P atoms
        d = np.linalg.norm(P_coords - o[None, :], axis=1)
        # Exclude self if present in P list
        for k, j in enumerate(P_idx):
            if j == i:
                d[k] = np.inf
        kmin = int(np.argmin(d))
        dmin = float(d[kmin])
        if dmin < dist_cutoff:
            j = P_idx[kmin]
            # Ensure unique incoming mapping by keeping the closer one
            if j in next_map.values():
                # Find existing i0 such that next_map[i0]==j
                i0 = next(ii for ii, jj in next_map.items() if jj == j)
                if dmin < dist_map[i0]:
                    next_map.pop(i0)
                    dist_map.pop(i0)
                    next_map[i] = j
                    dist_map[i] = dmin
            else:
                next_map[i] = j
                dist_map[i] = dmin

    return next_map, dist_map


def connected_components_from_next(n_nodes: int, next_map: Dict[int, int]) -> List[List[int]]:
    # Undirected adjacency
    adj: List[List[int]] = [[] for _ in range(n_nodes)]
    for i, j in next_map.items():
        adj[i].append(j)
        adj[j].append(i)

    seen = [False] * n_nodes
    comps: List[List[int]] = []
    for i in range(n_nodes):
        if seen[i]:
            continue
        # BFS
        stack = [i]
        seen[i] = True
        comp = []
        while stack:
            v = stack.pop()
            comp.append(v)
            for w in adj[v]:
                if not seen[w]:
                    seen[w] = True
                    stack.append(w)
        comps.append(comp)
    return comps


def order_component_5to3(comp: List[int], next_map: Dict[int, int]) -> List[int]:
    prev: Dict[int, int] = {}
    for i, j in next_map.items():
        prev[j] = i

    # pick start: node in comp with no prev inside comp
    comp_set = set(comp)
    starts = [i for i in comp if i not in prev or prev[i] not in comp_set]
    if not starts:
        # cycle or ambiguous; fall back
        start = comp[0]
    else:
        start = min(starts)

    order: List[int] = []
    seen = set()
    cur = start
    while cur is not None and cur in comp_set and cur not in seen:
        order.append(cur)
        seen.add(cur)
        cur = next_map.get(cur)

    # If we didn't include all nodes (broken links), append remaining in arbitrary order
    if len(order) != len(comp):
        remaining = [i for i in comp if i not in seen]
        order.extend(sorted(remaining))

    return order


def make_ter_record(chainID: str, resName: str, resSeq: int) -> pdb_ter_record:
    # Serial will be re-numbered by rec2file(reorder_serial=True)
    line = f"TER   {0:5d}      {resName:>3} {chainID}{resSeq:4d}\n"
    return pdb_ter_record(line)




def _core_outer_basepair(core: Structure, core_end: str) -> Tuple[ResidKey, ResidKey]:
    """Return the outermost basepair ResidKeys of a positioned core at the requested end.

    core_end:
      'B' -> outermost B-end bp (E13/F24)
      'Z' -> outermost Z-end bp (E9/F28)

    Returned in the core's internal strand order (E, F).
    """

    if core_end == 'B':
        (a, b) = core_BZ.B_END_BASEPAIRS[-1]
    elif core_end == 'Z':
        (a, b) = core_BZ.Z_END_BASEPAIRS[-1]
    else:
        raise ValueError(f"core_end must be 'B' or 'Z', got {core_end}")

    ka: ResidKey = (core.seg_id, a[0], int(a[1]))
    kb: ResidKey = (core.seg_id, b[0], int(b[1]))
    return ka, kb


def _helix_anchor_basepair(helix: Structure, end: str) -> Tuple[ResidKey, ResidKey]:
    """Return the basepair (ResidKeys) that becomes the helix *anchor* after trimming 2 bp.

    If we trim 2 bp at a given end, the *third* bp from that end is the one that remains
    closest to the junction and is the appropriate residue pair to connect to the core.

    Returned in the helix's internal strand order.
    """

    # Need at least 3 bp to define the anchor.
    bps3 = helix.end_basepairs(end, n_bp=3)
    return bps3[0]



def _add_edge(adj: Dict[ResidKey, set], a: ResidKey, b: ResidKey) -> None:
    adj.setdefault(a, set()).add(b)
    adj.setdefault(b, set()).add(a)


def _distance_min_O3P(resA: Residue, resB: Residue) -> Optional[float]:
    """Return the smaller of O3'(A)->P(B) and O3'(B)->P(A) distances (A)."""

    def P(res: Residue):
        rec = res.atom_by_name.get('P')
        if rec is None:
            return None
        return np.array([rec.x, rec.y, rec.z], dtype=float)

    def O3(res: Residue):
        return res.xyz("O3'")

    PA, PB = P(resA), P(resB)
    OA, OB = O3(resA), O3(resB)
    d = []
    if OA is not None and PB is not None:
        d.append(float(np.linalg.norm(OA - PB)))
    if OB is not None and PA is not None:
        d.append(float(np.linalg.norm(OB - PA)))
    if not d:
        return None
    return min(d)


def build_explicit_backbone_graph(structs: Sequence[Structure], junctions: Sequence[JunctionInfo]) -> Dict[ResidKey, set]:
    """Build an explicit undirected backbone graph using known residue order + junction mapping.

    Why this exists:
      The older approach tried to infer backbone connectivity by global nearest-neighbour O3'-P
      distances. At junctions (and when helices are close in space) that can miss or mis-assign
      links, producing multiple disconnected components.

    Here we:
      1) Add edges within each structure chain by sequence order (resSeq) for the two main chains.
      2) Add 4 edges per junction (2 at fixed-core + 2 at core-next), one per strand.

    The result should be exactly 2 components (2 DNA strands).
    """

    adj: Dict[ResidKey, set] = {}

    # Internal chain edges
    for st in structs:
        for chainID in st.chains:
            keys = [
                k for k, r in st.residues.items()
                if r.chainID == chainID and k not in st.pre_trim and k not in st.trim
            ]
            keys.sort(key=lambda k: st.residues[k].resSeq)
            for k1, k2 in zip(keys, keys[1:]):
                _add_edge(adj, k1, k2)

    # Junction edges
    for jx in junctions:
        fixed_bp = _helix_anchor_basepair(jx.fixed, jx.fixed_end)
        core_bp_fixed = _core_outer_basepair(jx.core, jx.core_end_fixed)

        if not jx.swap_fixed_to_core:
            _add_edge(adj, fixed_bp[0], core_bp_fixed[0])
            _add_edge(adj, fixed_bp[1], core_bp_fixed[1])
        else:
            _add_edge(adj, fixed_bp[0], core_bp_fixed[1])
            _add_edge(adj, fixed_bp[1], core_bp_fixed[0])

        next_bp = _helix_anchor_basepair(jx.next_helix, jx.next_end)
        core_bp_next = _core_outer_basepair(jx.core, jx.core_end_next)

        if not jx.swap_next_to_core:
            _add_edge(adj, next_bp[0], core_bp_next[0])
            _add_edge(adj, next_bp[1], core_bp_next[1])
        else:
            _add_edge(adj, next_bp[0], core_bp_next[1])
            _add_edge(adj, next_bp[1], core_bp_next[0])

    return adj


def connected_components_keys(adj: Dict[ResidKey, set], nodes: List[ResidKey]) -> List[List[ResidKey]]:
    seen = set()
    comps: List[List[ResidKey]] = []
    node_set = set(nodes)

    for n in nodes:
        if n in seen:
            continue
        stack = [n]
        seen.add(n)
        comp = []
        while stack:
            v = stack.pop()
            comp.append(v)
            for w in adj.get(v, set()):
                if w in node_set and w not in seen:
                    seen.add(w)
                    stack.append(w)
        comps.append(comp)

    return comps


def order_path_component_keys(adj: Dict[ResidKey, set], comp: List[ResidKey]) -> List[ResidKey]:
    """Order a component that should represent a simple path (DNA strand)."""

    comp_set = set(comp)
    degrees = {k: len([n for n in adj.get(k, set()) if n in comp_set]) for k in comp}

    ends = [k for k, d in degrees.items() if d == 1]
    if ends:
        start = sorted(ends, key=lambda k: (k[0], k[1], k[2]))[0]
    else:
        start = sorted(comp, key=lambda k: (k[0], k[1], k[2]))[0]

    order: List[ResidKey] = []
    prev = None
    cur = start

    for _ in range(len(comp)):
        order.append(cur)
        neigh = [n for n in adj.get(cur, set()) if n in comp_set and n != prev]
        if not neigh:
            break
        # Deterministic choice if something goes wrong (branching)
        neigh = sorted(neigh, key=lambda k: (k[0], k[1], k[2]))
        nxt = neigh[0]
        prev, cur = cur, nxt

    if len(order) != len(comp):
        remaining = [k for k in comp if k not in set(order)]
        order.extend(sorted(remaining, key=lambda k: (k[0], k[1], k[2])))

    return order


def _p_xyz(res: Residue) -> Optional[np.ndarray]:
    rec = res.atom_by_name.get('P')
    if rec is None:
        return None
    return np.array([rec.x, rec.y, rec.z], dtype=float)


def _o3_xyz(res: Residue) -> Optional[np.ndarray]:
    # alias support handled by Residue.xyz
    return res.xyz("O3'")


def _median(values: List[float]) -> float:
    if not values:
        raise ValueError('median of empty list')
    vals = sorted(values)
    n = len(vals)
    mid = n // 2
    if n % 2 == 1:
        return float(vals[mid])
    return float(0.5 * (vals[mid - 1] + vals[mid]))


def ensure_order_5to3(
    *,
    order: List[ResidKey],
    res_by_key: Dict[ResidKey, Residue],
    verbose_label: str,
) -> List[ResidKey]:
    '''Ensure residue order follows 5'->3' direction.

    We compare typical phosphodiester distances for the proposed order:
        forward:  d(O3'(i) -> P(i+1))
        backward: d(O3'(i+1) -> P(i))

    In a correctly oriented 5'->3' ordering, forward distances should be ~1.6–2.0 A.
    If the backward distances are consistently smaller, we reverse the order.
    '''

    if len(order) < 2:
        return order

    fwd: List[float] = []
    bwd: List[float] = []

    for a_key, b_key in zip(order[:-1], order[1:]):
        a = res_by_key.get(a_key)
        b = res_by_key.get(b_key)
        if a is None or b is None:
            continue
        o3_a = _o3_xyz(a)
        p_a = _p_xyz(a)
        o3_b = _o3_xyz(b)
        p_b = _p_xyz(b)

        if o3_a is not None and p_b is not None:
            fwd.append(float(np.linalg.norm(o3_a - p_b)))
        if o3_b is not None and p_a is not None:
            bwd.append(float(np.linalg.norm(o3_b - p_a)))

    if not fwd or not bwd:
        print(f"{verbose_label} WARNING: cannot determine 5'/3' direction (missing O3'/P). Keeping current order.")
        return order

    # Prefer a robust statistic: use the median of 'bond-like' distances when possible.
    fwd_small = [d for d in fwd if d < 4.0]
    bwd_small = [d for d in bwd if d < 4.0]

    f_stat = _median(fwd_small) if fwd_small else _median(fwd)
    b_stat = _median(bwd_small) if bwd_small else _median(bwd)

    flipped = False
    if b_stat < f_stat:
        order = list(reversed(order))
        flipped = True

    status = "reversed to 5'->3'" if flipped else "kept"

    print(
        f"{verbose_label} strand direction check: median d(O3(i)->P(i+1))={f_stat:.3f} A, "
        f"median d(O3(i+1)->P(i))={b_stat:.3f} A -> {status}"
    )

    return order


def write_ligated_pdb_explicit(
    *,
    structs: Sequence[Structure],
    junctions: Sequence[JunctionInfo],
    out_path: Path,
) -> None:
    """Write final ligated PDB using explicit connectivity (no global nearest-neighbour guessing)."""

    # Gather all kept residues
    res_by_key: Dict[ResidKey, Residue] = {}
    for st in structs:
        for k, r in st.residues.items():
            if k in st.pre_trim or k in st.trim:
                continue
            res_by_key[k] = r

    nodes = sorted(res_by_key.keys(), key=lambda k: (k[0], k[1], k[2]))
    print(f"Total residues after trimming (all segments + cores): {len(nodes)}")

    adj = build_explicit_backbone_graph(structs, junctions)

    # Report junction edge distances for sanity
    for jx in junctions:
        print(f"[J{jx.jid}] explicit bonds (min O3'-P distances):")

        fixed_bp = _helix_anchor_basepair(jx.fixed, jx.fixed_end)
        core_bp_fixed = _core_outer_basepair(jx.core, jx.core_end_fixed)

        pairs_fixed = []
        if not jx.swap_fixed_to_core:
            pairs_fixed = [(fixed_bp[0], core_bp_fixed[0]), (fixed_bp[1], core_bp_fixed[1])]
        else:
            pairs_fixed = [(fixed_bp[0], core_bp_fixed[1]), (fixed_bp[1], core_bp_fixed[0])]

        for a, b in pairs_fixed:
            d = _distance_min_O3P(res_by_key[a], res_by_key[b])
            d_str = f"{d:.3f} A" if d is not None else 'NA'
            print(f"   fixed[{jx.fixed.name}] <-> core[{jx.core.seg_id}] ({a[1]}{a[2]}-{b[1]}{b[2]}): {d_str}")

        next_bp = _helix_anchor_basepair(jx.next_helix, jx.next_end)
        core_bp_next = _core_outer_basepair(jx.core, jx.core_end_next)

        pairs_next = []
        if not jx.swap_next_to_core:
            pairs_next = [(next_bp[0], core_bp_next[0]), (next_bp[1], core_bp_next[1])]
        else:
            pairs_next = [(next_bp[0], core_bp_next[1]), (next_bp[1], core_bp_next[0])]

        for a, b in pairs_next:
            d = _distance_min_O3P(res_by_key[a], res_by_key[b])
            d_str = f"{d:.3f} A" if d is not None else 'NA'
            print(f"   next[{jx.next_helix.name}] <-> core[{jx.core.seg_id}] ({a[1]}{a[2]}-{b[1]}{b[2]}): {d_str}")

    comps = connected_components_keys(adj, nodes)
    comps.sort(key=len, reverse=True)
    print(f"Explicit ligation graph: components={len(comps)} sizes={[len(c) for c in comps]}")

    if len(comps) < 2:
        raise ValueError(f"Explicit ligation expected 2 components (2 strands), found {len(comps)}")

    compA, compB = comps[0], comps[1]

    if len(compA) + len(compB) != len(nodes):
        extra = sum(len(c) for c in comps[2:])
        print(
            f"WARNING: explicit graph produced extra components (extra_residues={extra}). "
            f"They will be appended deterministically to strands."
        )
        toggle = 0
        for c in comps[2:]:
            if toggle == 0:
                compA.extend(c)
            else:
                compB.extend(c)
            toggle = 1 - toggle

    orderA = order_path_component_keys(adj, compA)
    orderB = order_path_component_keys(adj, compB)

    # Ensure both strands are numbered 5'->3' (some components can be discovered in reverse).
    orderA = ensure_order_5to3(order=orderA, res_by_key=res_by_key, verbose_label="[strand A]")
    orderB = ensure_order_5to3(order=orderB, res_by_key=res_by_key, verbose_label="[strand B]")

    print("Final ligation (explicit):")
    print(f"  Strand A residues: {len(orderA)}")
    print(f"  Strand B residues: {len(orderB)}")

    out_recs: List[object] = []

    for chainID, order in [('A', orderA), ('B', orderB)]:
        for new_seq, key in enumerate(order, start=1):
            res = res_by_key[key]
            for a in res.atoms:
                a.update_chainID(chainID)
                a.update_resSeq(new_seq)
            out_recs.extend(res.atoms)

        last_res = res_by_key[order[-1]]
        out_recs.append(make_ter_record(chainID, last_res.resName, len(order)))

    with out_path.open('w') as f:
        rec2file(out_recs, f, reorder_serial=True)
        f.write('END\n')

    print(f"Wrote output PDB: {out_path}")


def write_ligated_pdb(nodes: List[ResidueNode], next_map: Dict[int, int], out_path: Path) -> None:
    comps = connected_components_from_next(len(nodes), next_map)
    comps.sort(key=len, reverse=True)

    if len(comps) < 2:
        raise ValueError(f"Expected 2 backbone components (2 strands), found {len(comps)}")

    # Take the two largest components as the two strands
    compA, compB = comps[0], comps[1]

    orderA = order_component_5to3(compA, next_map)
    orderB = order_component_5to3(compB, next_map)

    print(f"Final ligation: detected {len(comps)} backbone components; using top-2 as strands:")
    print(f"  Strand A residues: {len(orderA)}")
    print(f"  Strand B residues: {len(orderB)}")
    if len(comps) > 2:
        extra = [len(c) for c in comps[2:]]
        print(f"  WARNING: {len(comps)-2} extra small components present (sizes={extra}). They will be ignored.")

    out_recs: List[object] = []

    # Assign chain IDs and renumber residues
    for chainID, order in [('A', orderA), ('B', orderB)]:
        for new_seq, idx in enumerate(order, start=1):
            res = nodes[idx].residue
            # Update all atoms in residue
            for a in res.atoms:
                a.update_chainID(chainID)
                a.update_resSeq(new_seq)
            # Preserve original atom order
            out_recs.extend(res.atoms)
        # TER
        last_res = nodes[order[-1]].residue
        out_recs.append(make_ter_record(chainID, last_res.resName, len(order)))

    with out_path.open('w') as f:
        rec2file(out_recs, f, reorder_serial=True)
        f.write('END\n')

    print(f"Wrote output PDB: {out_path}")


def write_raw_aligned_pdb(*, structs: Sequence[Structure], out_path: Path) -> None:
    '''Write an aligned-but-unligated PDB for inspection.

    This outputs all structures as currently positioned after alignment, before
    junction-overlap trimming and final ligation. Z-DNA residues removed by the
    automatic terminal-phase preprocessing are excluded, because those residues are
    not used during alignment or final assembly.
    '''

    out_recs: List[object] = []
    for st in structs:
        for chainID in st.chains:
            keys = [k for k, r in st.residues.items() if r.chainID == chainID and k not in st.pre_trim]
            keys.sort(key=lambda k: st.residues[k].resSeq)
            if not keys:
                continue
            for key in keys:
                out_recs.extend(st.residues[key].atoms)
            last_res = st.residues[keys[-1]]
            out_recs.append(make_ter_record(chainID, last_res.resName, last_res.resSeq))

    with out_path.open('w') as f:
        rec2file(out_recs, f, reorder_serial=True)
        f.write('END\n')

    print(f"Wrote aligned-raw PDB (no junction trimming/ligation): {out_path}")



# ----------------------------
# Main
# ----------------------------

def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Build multi-segment B/Z DNA connected by BZ junction cores.")
    p.add_argument('--gui', action='store_true', help='Launch GUI mode.')
    p.add_argument('dna_files', nargs='*', help="Input PDB files, alternating B then Z then B ...")
    p.add_argument('--out', default=DEFAULT_OUTPUT_NAME, help='Output PDB filename')
    p.add_argument(
        '--axis-mode',
        choices=['collinear', 'codirectional', 'none'],
        default=None,
        help=(
            "Axis treatment across each junction. Default: codirectional (direction alignment only, no lateral shift). "
            "collinear = optional strict direction + perpendicular axis-line shift; none = no post-fit axis correction."
        ),
    )
    p.add_argument(
        '--collinear',
        choices=['y', 'n', 'direction', 'codirectional', 'co-directional', 'collinear'],
        default=None,
        help=(
            "Backward-compatible alias: y/direction/codirectional=--axis-mode codirectional; "
            "n=--axis-mode none. Use --axis-mode collinear for strict same-line correction. "
            "Prefer --axis-mode for new runs."
        ),
    )
    p.add_argument(
        '--axis-source',
        choices=['auto', 'dssr', 'pca'],
        default='auto',
        help=(
            "Axis source for post-fit axis correction. Default: auto (import align2z.py and try DSSR --more first; "
            "fall back to C1' PCA if DSSR is unavailable). dssr = require DSSR; pca = original PCA estimate."
        ),
    )
    p.add_argument('--dist_cutoff', type=float, default=2.2, help="Reserved legacy option; explicit ligation is used")
    p.add_argument(
        '--no-z-auto-trim',
        action='store_true',
        help='Disable automatic Z-DNA terminal pre-trimming; stop with an error if a Z model fails the requirement.',
    )
    return p


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    return build_arg_parser().parse_args(argv)


def effective_axis_mode(args: argparse.Namespace) -> str:
    """Resolve --axis-mode plus legacy --collinear into one internal mode."""

    if getattr(args, 'axis_mode', None) is not None:
        if getattr(args, 'collinear', None) is not None:
            print(f"NOTE: --axis-mode {args.axis_mode} overrides legacy --collinear {args.collinear}.")
        return normalize_axis_mode(args.axis_mode)
    if getattr(args, 'collinear', None) is not None:
        return normalize_axis_mode(args.collinear)
    return 'codirectional'


def effective_axis_source(args: argparse.Namespace) -> str:
    """Resolve and validate --axis-source."""

    source = getattr(args, 'axis_source', 'auto')
    src = (source or 'auto').strip().lower()
    if src not in ('auto', 'dssr', 'pca'):
        raise ValueError(f"Unknown axis source: {source}")
    return src

def resolve_output_path(out_text: str, input_paths: Sequence[Path]) -> Path:
    """Resolve output path; parser default goes to the first input file's folder."""

    out_path = Path(out_text)
    if out_text == DEFAULT_OUTPUT_NAME and not out_path.is_absolute() and input_paths:
        first_parent = input_paths[0].expanduser().resolve().parent
        return first_parent / DEFAULT_OUTPUT_NAME
    return out_path


def raw_output_path(out_path: Path) -> Path:
    if out_path.suffix:
        return out_path.with_name(out_path.stem + '_raw' + out_path.suffix)
    return out_path.with_name(out_path.name + '_raw.pdb')


def run_pipeline(args: argparse.Namespace) -> None:
    axis_mode = effective_axis_mode(args)
    paths = [Path(p) for p in args.dna_files]
    for p in paths:
        if not p.exists():
            raise SystemExit(f"ERROR: input file not found: {p}")

    n_files = len(paths)
    if n_files < 2:
        raise SystemExit("ERROR: need at least 2 files (B1 Z1)")

    # Assign types by position: B, Z, B, Z, ...
    types = ['B' if i % 2 == 0 else 'Z' for i in range(n_files)]
    nB = sum(1 for t in types if t == 'B')
    nZ = sum(1 for t in types if t == 'Z')
    if nB < 1 or nZ < 1:
        raise SystemExit("ERROR: need >=1 B model and >=1 Z model")
    if nB < nZ:
        raise SystemExit(f"ERROR: number of B models must be >= number of Z models (got B={nB}, Z={nZ})")


    print("Input files (assumed alternating B/Z by order):")
    for i, (t, p) in enumerate(zip(types, paths), start=1):
        print(f"  {i:2d}. {t}  {p}")
    print(f"Junctions to build: {n_files - 1} -> cores to insert: {n_files - 1}")
    print(f"Axis correction mode: {axis_mode}")
    axis_source = effective_axis_source(args)
    print(f"Axis source: {axis_source}")
    if axis_source == 'auto':
        print("  auto = try DSSR axis via imported align2z.py; fall back to PCA if unavailable.")
    elif axis_source == 'dssr':
        print("  dssr = require DSSR axis via imported align2z.py; stop if unavailable.")
    else:
        print("  pca = use internal C1' PCA axis estimate only.")
    if axis_mode == 'collinear':
        print("  collinear = rotate axes parallel, then translate moving helix so the fitted axis lines coincide (optional strict mode).")
    elif axis_mode == 'codirectional':
        print("  codirectional = rotate axes parallel only; no lateral axis-line shift (default).")
    else:
        print("  none = no post-fit axis correction.")
    print(
        "Z-DNA requirement: every selected Z chain should start with pyrimidine (C/T/U) "
        "and end with purine (A/G)."
    )

    # Load helices and preprocess Z-DNA terminal phase if needed.
    helices: List[Structure] = []
    for idx, (p, t) in enumerate(zip(paths, types)):
        seg_id = f"seg{idx+1}"
        st = load_helix(p, seg_id=seg_id)
        if t == 'Z':
            if args.no_z_auto_trim:
                ok, messages = _z_requirement_status(st)
                if not ok:
                    for msg in messages:
                        print(f"  Z-check failed for {p.name}: {msg}")
                    raise SystemExit(
                        f"ERROR: Z-DNA file {p.name} does not satisfy the required terminal phase and --no-z-auto-trim was used."
                    )
                print(f"  Z-check OK for {p.name}: each main chain starts with pyrimidine and ends with purine.")
                for msg in messages:
                    print(f"    {msg}")
            else:
                apply_z_auto_trim_if_needed(st, p.name)
        helices.append(st)
        chain_counts = {
            c: sum(1 for r in st.residues.values() if r.chainID == c and r.key not in st.pre_trim)
            for c in st.chains
        }
        print(f"Loaded {p.name}: chains={st.chains} active_residue_counts={chain_counts} basepairs={len(st.basepairs)}")

    # First helix: treat its 'start' as backward terminus, so we connect forward from 'end' by default.
    helices[0].backward_end = 'start'

    all_structs: List[Structure] = [helices[0]]
    junctions: List[JunctionInfo] = []

    # Build junctions sequentially.
    for j in range(n_files - 1):
        fixed = helices[j]
        moving_helix = helices[j + 1]

        junction_id = j + 1
        prefix = f"[J{junction_id}]"

        t_fixed = types[j]
        t_next = types[j + 1]

        if (t_fixed, t_next) == ('B', 'Z'):
            core_end_fixed = 'B'
            core_end_next = 'Z'
        elif (t_fixed, t_next) == ('Z', 'B'):
            core_end_fixed = 'Z'
            core_end_next = 'B'
        else:
            raise SystemExit(f"ERROR: input files must strictly alternate B/Z; got {t_fixed}->{t_next} at junction {junction_id}")

        fixed_end = fixed.forward_end()

        # Create and align a fresh core to the fixed helix. For the first junction, try both
        # ends of the first helix, and prefer core placements that point outward from that end.
        if j == 0:
            other_end = 'start' if fixed_end == 'end' else 'end'
            best_good = None
            best_any = None
            for try_end in (fixed_end, other_end):
                core_try = new_core(seg_id=f"core{junction_id}")
                rmsd_try, swap_try = align_moving_to_fixed(
                    fixed=fixed,
                    fixed_end=try_end,
                    moving=core_try,
                    moving_end_kind='core',
                    core_end=core_end_fixed,
                    verbose_prefix=prefix + ' [try]',
                )

                fixed_out = end_outward_vector(fixed, try_end)
                core_dir = core_through_vector(core_try, core_end_fixed, core_end_next)
                dot_dir = float(np.dot(core_dir, fixed_out))
                print(f"{prefix} [try] direction check: dot(core_dir, fixed_out)={dot_dir:.3f} (try_end={try_end})")

                cand = (rmsd_try, try_end, core_try, swap_try, dot_dir)
                if best_any is None or rmsd_try < best_any[0]:
                    best_any = cand
                if dot_dir > 0:
                    if best_good is None or rmsd_try < best_good[0]:
                        best_good = cand

            assert best_any is not None
            chosen = best_good if best_good is not None else best_any
            _rmsd_best, fixed_end, core, swap_fixed, dot_dir = chosen
            if best_good is None:
                print(f"{prefix} WARNING: could not find an outward-pointing core placement; using lowest RMSD")
            fixed.backward_end = 'start' if fixed_end == 'end' else 'end'
            print(f"{prefix} selected fixed_end={fixed_end} for first junction (backward_end={fixed.backward_end})")
        else:
            core = new_core(seg_id=f"core{junction_id}")
            _rmsd1, swap_fixed = align_moving_to_fixed(
                fixed=fixed,
                fixed_end=fixed_end,
                moving=core,
                moving_end_kind='core',
                core_end=core_end_fixed,
                verbose_prefix=prefix,
            )
            fixed_out = end_outward_vector(fixed, fixed_end)
            core_dir = core_through_vector(core, core_end_fixed, core_end_next)
            dot_dir = float(np.dot(core_dir, fixed_out))
            if dot_dir <= 0:
                print(
                    f"{prefix} WARNING: core through-vector is not pointing outward from fixed helix end "
                    f"(dot={dot_dir:.3f}). This may indicate an orientation problem."
                )

        if j == 0:
            print(f"{prefix} using core aligned to fixed_end={fixed_end} (auto-selected)")

        junction_dir = core_through_vector(core, core_end_fixed, core_end_next)

        # Align next helix to the other end of the core.
        preferred_next_end = 'start'
        chosen_end, rmsd2, swap_next, pivot, dot_ext = align_helix_to_core(
            helix=moving_helix,
            preferred_end=preferred_next_end,
            core=core,
            core_end=core_end_next,
            junction_dir=junction_dir,
            verbose_prefix=prefix,
            auto_switch_if_better=True,
        )
        moving_helix.backward_end = chosen_end

        if dot_ext <= 0:
            print(
                f"{prefix} WARNING: next helix extension is not forward along junction_dir (dir_cos={dot_ext:.3f}). "
                "The model may overlap/fold-back."
            )

        if axis_mode != 'none':
            enforce_axis_alignment(
                fixed_helix=fixed,
                moving_helix=moving_helix,
                pivot=pivot,
                junction_dir=junction_dir,
                verbose_prefix=prefix,
                mode=axis_mode,
                axis_source=axis_source,
            )

        # Mark overlapping basepairs for deletion:
        #   fixed: delete its forward end 2 bp
        #   moving helix: delete its backward end 2 bp
        fixed_bps_to_trim = fixed.end_basepairs(fixed_end, n_bp=2)
        moving_bps_to_trim = moving_helix.end_basepairs(chosen_end, n_bp=2)

        for bp in fixed_bps_to_trim:
            fixed.trim.update(bp)
        for bp in moving_bps_to_trim:
            moving_helix.trim.update(bp)

        print(f"{prefix} trim: fixed[{fixed.name}] {fixed_end}-end 2 bp (residues={len(fixed_bps_to_trim)*2})")
        print(f"{prefix} trim: helix[{moving_helix.name}] {chosen_end}-end 2 bp (residues={len(moving_bps_to_trim)*2})")

        junctions.append(JunctionInfo(
            jid=junction_id,
            fixed=fixed,
            fixed_end=fixed_end,
            core=core,
            core_end_fixed=core_end_fixed,
            swap_fixed_to_core=swap_fixed,
            next_helix=moving_helix,
            next_end=chosen_end,
            core_end_next=core_end_next,
            swap_next_to_core=swap_next,
        ))

        all_structs.append(core)
        if moving_helix not in all_structs:
            all_structs.append(moving_helix)

    out_path = resolve_output_path(args.out, paths)
    if str(out_path) != str(Path(args.out)):
        print(f"Output path defaulted to the first input folder: {out_path}")
    write_raw_aligned_pdb(structs=all_structs, out_path=raw_output_path(out_path))
    write_ligated_pdb_explicit(structs=all_structs, junctions=junctions, out_path=out_path)


def launch_gui() -> None:
    """Open a small Tkinter GUI for make_BZ parameters."""

    try:
        import tkinter as tk
        from tkinter import filedialog, messagebox, scrolledtext
    except Exception as exc:
        print(f"ERROR: GUI mode requires tkinter, but it could not be imported: {exc}")
        print("Use CLI mode instead, e.g.: python make_BZV2_3.py --axis-mode codirectional --out multi_BZ.pdb B1.pdb Z1.pdb")
        return

    try:
        root = tk.Tk()
    except Exception as exc:
        print(f"ERROR: could not open the Tkinter GUI: {exc}")
        print("Use CLI mode instead, e.g.: python make_BZV2_3.py --axis-mode codirectional --out multi_BZ.pdb B1.pdb Z1.pdb")
        return

    root.title("make_BZ - B/Z junction builder")

    dna_files_var = tk.StringVar()
    out_var = tk.StringVar(value=DEFAULT_OUTPUT_NAME)
    out_default_mode = {"value": True}
    axis_mode_var = tk.StringVar(value="codirectional")
    auto_trim_var = tk.BooleanVar(value=True)
    axis_source_var = tk.StringVar(value="auto")

    frm = tk.Frame(root, padx=10, pady=10)
    frm.grid(row=0, column=0, sticky="nsew")
    root.columnconfigure(0, weight=1)
    root.rowconfigure(0, weight=1)
    frm.columnconfigure(1, weight=1)

    tk.Label(frm, text="DNA input files (must alternate B, Z, B, Z...):").grid(row=0, column=0, columnspan=3, sticky="w")
    files_text = scrolledtext.ScrolledText(frm, width=80, height=7)
    files_text.grid(row=1, column=0, columnspan=3, sticky="nsew", pady=(2, 8))
    frm.rowconfigure(1, weight=1)

    def _input_default_dir() -> str:
        files = [line.strip() for line in files_text.get("1.0", "end").splitlines() if line.strip()]
        if files:
            return str(Path(files[0]).expanduser().resolve().parent)
        return str(Path.cwd())

    def _out_is_default_like() -> bool:
        current = out_var.get().strip()
        if not current:
            return True
        p = Path(current)
        return p.name == DEFAULT_OUTPUT_NAME and out_default_mode["value"]

    def _set_default_output_path(text: str) -> None:
        out_default_mode["value"] = True
        out_var.set(text)

    def _update_default_output_from_inputs() -> None:
        files = [line.strip() for line in files_text.get("1.0", "end").splitlines() if line.strip()]
        if files and _out_is_default_like():
            _set_default_output_path(str(Path(files[0]).expanduser().resolve().parent / DEFAULT_OUTPUT_NAME))

    def add_files() -> None:
        selected = filedialog.askopenfilenames(title="Choose B/Z input PDB files in alternating order")
        if selected:
            current = files_text.get("1.0", "end").strip()
            add_text = "\n".join(selected)
            files_text.delete("1.0", "end")
            files_text.insert("1.0", (current + "\n" + add_text).strip() if current else add_text)
            _update_default_output_from_inputs()

    def clear_files() -> None:
        files_text.delete("1.0", "end")

    tk.Button(frm, text="Add input files...", command=add_files).grid(row=2, column=0, sticky="w")
    tk.Button(frm, text="Clear", command=clear_files).grid(row=2, column=1, sticky="w")

    tk.Label(frm, text="Output PDB:").grid(row=3, column=0, sticky="w", pady=(8, 2))
    out_entry = tk.Entry(frm, textvariable=out_var, width=60)
    out_entry.grid(row=3, column=1, sticky="ew", pady=(8, 2))

    def choose_out() -> None:
        current_out = Path(out_var.get().strip() or DEFAULT_OUTPUT_NAME)
        initialfile = current_out.name or DEFAULT_OUTPUT_NAME
        initialdir = str(current_out.parent) if str(current_out.parent) not in ("", ".") else _input_default_dir()
        selected = filedialog.asksaveasfilename(
            title="Choose output PDB",
            initialdir=initialdir,
            initialfile=initialfile,
            defaultextension=".pdb",
            filetypes=[("PDB files", "*.pdb"), ("All files", "*")],
        )
        if selected:
            out_default_mode["value"] = False
            out_var.set(selected)

    tk.Button(frm, text="Browse...", command=choose_out).grid(row=3, column=2, sticky="e", pady=(8, 2))

    tk.Label(frm, text="Axis correction mode:").grid(row=4, column=0, sticky="w")
    tk.Radiobutton(
        frm,
        text="Co-directional only (default: direction only, no lateral shift)",
        variable=axis_mode_var,
        value="codirectional",
        wraplength=760,
        justify="left",
    ).grid(row=4, column=1, columnspan=2, sticky="w")
    tk.Radiobutton(
        frm,
        text="True collinear (optional strict mode: direction + lateral shift so fitted axis lines coincide)",
        variable=axis_mode_var,
        value="collinear",
        wraplength=760,
        justify="left",
    ).grid(row=5, column=1, columnspan=2, sticky="w")
    tk.Radiobutton(
        frm,
        text="None (no post-fit axis correction)",
        variable=axis_mode_var,
        value="none",
        wraplength=760,
        justify="left",
    ).grid(row=6, column=1, columnspan=2, sticky="w")

    tk.Label(frm, text="Axis source:").grid(row=7, column=0, sticky="w")
    tk.OptionMenu(frm, axis_source_var, "auto", "dssr", "pca").grid(row=7, column=1, sticky="w")
    tk.Label(
        frm,
        text="auto = import align2z.py and use DSSR --more when available; fallback to C1' PCA",
        justify="left",
        wraplength=620,
    ).grid(row=7, column=1, columnspan=2, sticky="w", padx=(90, 0))

    tk.Checkbutton(
        frm,
        text="Auto-trim terminal Z-DNA bp if needed (required for DSSR/bnp_na-generated Z-DNA; input should be 2 bp longer than the target final Z segment)",
        variable=auto_trim_var,
        wraplength=760,
        justify="left",
    ).grid(row=8, column=0, columnspan=3, sticky="w")

    log = scrolledtext.ScrolledText(frm, width=90, height=16)
    log.grid(row=10, column=0, columnspan=3, sticky="nsew", pady=(10, 0))
    frm.rowconfigure(10, weight=2)

    def log_write(text: str) -> None:
        log.insert("end", text)
        log.see("end")
        root.update_idletasks()

    def run_from_gui() -> None:
        files = [line.strip() for line in files_text.get("1.0", "end").splitlines() if line.strip()]
        if len(files) < 2:
            messagebox.showerror("make_BZ", "Please provide at least two files: B1 and Z1.")
            return
        if _out_is_default_like():
            _update_default_output_from_inputs()

        argv = [
            "--out",
            out_var.get().strip() or str(Path(_input_default_dir()) / DEFAULT_OUTPUT_NAME),
            "--axis-mode",
            axis_mode_var.get(),
            "--axis-source",
            axis_source_var.get(),
        ]
        if not auto_trim_var.get():
            argv.append("--no-z-auto-trim")
        argv.extend(files)

        parser = build_arg_parser()
        args = parser.parse_args(argv)

        script_name = Path(sys.argv[0]).name if sys.argv and sys.argv[0] else "make_BZV2_3.py"
        cli_cmd = " ".join(shlex.quote(x) for x in ["python", script_name] + argv)

        import contextlib
        import io
        buf = io.StringIO()
        buf.write("Equivalent CLI command:\n  " + cli_cmd + "\n\n")
        log.delete("1.0", "end")
        try:
            with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(buf):
                run_pipeline(args)
            log_write(buf.getvalue())
            resolved_out = resolve_output_path(args.out, [Path(f) for f in files])
            messagebox.showinfo("make_BZ", f"Done.\nOutput: {resolved_out}\nRaw: {raw_output_path(resolved_out)}")
        except BaseException as exc:
            log_write(buf.getvalue())
            log_write(f"\nERROR: {exc}\n")
            messagebox.showerror("make_BZ", str(exc))

    tk.Button(frm, text="Run make_BZ", command=run_from_gui).grid(row=9, column=0, sticky="w", pady=(10, 0))

    help_text = (
        "Tip: add files in the exact order B1, Z1, B2, Z2...\n"
        "Axis: codirectional is the default (rotation only, no lateral shift). True collinear is optional and may stretch junction contacts.\n"
        "Axis source: auto imports align2z.py and tries DSSR --more first, then falls back to C1' PCA if DSSR is unavailable.\n"
        "Z-DNA requirement: each selected Z chain should start with C/T/U and end with A/G. "
        "The auto-trim option removes at most 1 bp from each Z end to satisfy this requirement. For DSSR/bnp_na-generated Z inputs, prepare the original Z-DNA 2 bp longer than the target final Z segment."
    )
    tk.Label(frm, text=help_text, justify="left", wraplength=760).grid(row=9, column=1, columnspan=2, sticky="w", pady=(10, 0))

    root.mainloop()


def main(argv: Optional[Sequence[str]] = None) -> None:
    if argv is None:
        argv = sys.argv[1:]
    argv = list(argv)
    if len(argv) == 0 or '--gui' in argv:
        launch_gui()
        return
    args = parse_args(argv)
    if not args.dna_files:
        raise SystemExit("ERROR: no DNA input files provided (or run without args for GUI mode).")
    run_pipeline(args)


if __name__ == '__main__':
    main()
