#!/usr/bin/env python3
"""Write a simple XYZ coordinate-axis BILD helper file.

The default drawing marks the origin with a small sphere and draws red X,
yellow Y, and blue Z arrows from the origin. The output is a plain-text
Chimera/ChimeraX .bild file.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable, Sequence, Tuple


Vector3 = Tuple[float, float, float]


def _fmt(value: float) -> str:
    return f"{float(value):.6g}"


def _point_text(point: Vector3) -> str:
    return " ".join(_fmt(value) for value in point)


def _parse_xyz(text: str) -> Vector3:
    parts = text.replace(",", " ").split()
    if len(parts) != 3:
        raise ValueError(f"Expected three numbers for xyz, got: {text!r}")
    try:
        return float(parts[0]), float(parts[1]), float(parts[2])
    except Exception as exc:
        raise ValueError(f"Could not parse xyz values: {text!r}") from exc


def _arrow_line(start: Vector3, end: Vector3, width: float) -> str:
    head_radius = max(float(width) * 2.5, 1e-6)
    return (
        f".arrow {_point_text(start)} {_point_text(end)} "
        f"{_fmt(width)} {_fmt(head_radius)} 0.85"
    )


def xyz_bild_lines(
    *,
    origin: Vector3 = (0.0, 0.0, 0.0),
    length: float = 20.0,
    width: float = 1.0,
    sphere_radius: float = 0.5,
) -> list[str]:
    """Return BILD lines for an XYZ triad.

    Parameters
    ----------
    origin:
        Start point for all three arrows and center of the sphere.
    length:
        Arrow length along each positive coordinate axis.
    width:
        Arrow shaft radius. The arrow head radius is `2.5 * width`.
    sphere_radius:
        Radius of the origin marker sphere.
    """
    length = float(length)
    width = float(width)
    sphere_radius = float(sphere_radius)
    if length <= 0:
        raise ValueError("Arrow length must be positive.")
    if width <= 0:
        raise ValueError("Arrow width must be positive.")
    if sphere_radius < 0:
        raise ValueError("Sphere radius cannot be negative.")

    ox, oy, oz = origin
    x_end = (ox + length, oy, oz)
    y_end = (ox, oy + length, oz)
    z_end = (ox, oy, oz + length)

    lines = [
        ".comment Generated by xyz_bild.py",
        f".comment Origin: {_point_text(origin)}",
        f".comment Arrow length: {_fmt(length)}",
        f".comment Arrow width: {_fmt(width)}",
        f".sphere {_point_text(origin)} {_fmt(sphere_radius)}",
        ".color 1 0 0",
        _arrow_line(origin, x_end, width),
        ".color 1 1 0",
        _arrow_line(origin, y_end, width),
        ".color 0 0 1",
        _arrow_line(origin, z_end, width),
    ]
    return lines


def write_xyz_bild(
    out_path: Path | str,
    *,
    origin: Vector3 = (0.0, 0.0, 0.0),
    length: float = 20.0,
    width: float = 1.0,
    sphere_radius: float = 0.5,
) -> Path:
    """Write an XYZ coordinate-axis BILD file and return its path."""
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = xyz_bild_lines(origin=origin, length=length, width=width, sphere_radius=sphere_radius)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Write a Chimera/ChimeraX XYZ coordinate-axis .bild file.")
    parser.add_argument("-o", "--out", default="xyz_axes.bild", help="Output .bild file. Default: xyz_axes.bild")
    parser.add_argument("--origin", default="0 0 0", help="Origin xyz triplet. Default: '0 0 0'")
    parser.add_argument("--length", type=float, default=20.0, help="Length of each positive-axis arrow. Default: 20.0")
    parser.add_argument("--width", type=float, default=1.0, help="Arrow shaft radius. Default: 1.0")
    parser.add_argument("--sphere-radius", type=float, default=0.5, help="Origin sphere radius. Default: 0.5")
    return parser


def main(argv: Sequence[str] | None = None) -> None:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    origin = _parse_xyz(args.origin)
    out_path = write_xyz_bild(
        args.out,
        origin=origin,
        length=args.length,
        width=args.width,
        sphere_radius=args.sphere_radius,
    )
    print(f"Wrote XYZ BILD: {out_path}")


if __name__ == "__main__":
    main()
